/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.global.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-24-2008
 * 
 * XDoclet definition:
 * @struts.form name="carForm"
 */
public class CarForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** carSize property */
	private String carSize;
	
	/** carID property */
	private String carID;
	
	/** carNO property */
	private String carNO;

	/** leaveTime property */
	private String leaveTime;

	/** buyTime property */
	private String buyTime;

	/** carStateID property */
	private String carStateID;

	/** remark property */
	private String remark;

	/** workNO property */
	private String workNO;

	/** empID property */
	private String empID;

	/** lineID property */
	private String lineID;

	/** tonnage property */
	private String tonnage;

	/** carTypeID property */
	private String carTypeID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the carSize.
	 * @return String
	 */
	public String getCarSize() {
		return carSize;
	}

	/** 
	 * Set the carSize.
	 * @param carSize The carSize to set
	 */
	public void setCarSize(String carSize) {
		this.carSize = carSize;
	}

	/** 
	 * Returns the carNO.
	 * @return String
	 */
	public String getCarNO() {
		return carNO;
	}

	/** 
	 * Set the carNO.
	 * @param carNO The carNO to set
	 */
	public void setCarNO(String carNO) {
		this.carNO = carNO;
	}

	/** 
	 * Returns the leaveTime.
	 * @return String
	 */
	public String getLeaveTime() {
		return leaveTime;
	}

	/** 
	 * Set the leaveTime.
	 * @param leaveTime The leaveTime to set
	 */
	public void setLeaveTime(String leaveTime) {
		this.leaveTime = leaveTime;
	}

	/** 
	 * Returns the buyTime.
	 * @return String
	 */
	public String getBuyTime() {
		return buyTime;
	}

	/** 
	 * Set the buyTime.
	 * @param buyTime The buyTime to set
	 */
	public void setBuyTime(String buyTime) {
		this.buyTime = buyTime;
	}

	/** 
	 * Returns the carStateID.
	 * @return String
	 */
	public String getCarStateID() {
		return carStateID;
	}

	/** 
	 * Set the carStateID.
	 * @param carStateID The carStateID to set
	 */
	public void setCarStateID(String carStateID) {
		this.carStateID = carStateID;
	}

	/** 
	 * Returns the remark.
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/** 
	 * Set the remark.
	 * @param remark The remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/** 
	 * Returns the workNO.
	 * @return String
	 */
	public String getWorkNO() {
		return workNO;
	}

	/** 
	 * Set the workNO.
	 * @param workNO The workNO to set
	 */
	public void setWorkNO(String workNO) {
		this.workNO = workNO;
	}

	/** 
	 * Returns the empID.
	 * @return String
	 */
	public String getEmpID() {
		return empID;
	}

	/** 
	 * Set the empID.
	 * @param empID The empID to set
	 */
	public void setEmpID(String empID) {
		this.empID = empID;
	}

	/** 
	 * Returns the lineID.
	 * @return String
	 */
	public String getLineID() {
		return lineID;
	}

	/** 
	 * Set the lineID.
	 * @param lineID The lineID to set
	 */
	public void setLineID(String lineID) {
		this.lineID = lineID;
	}

	/** 
	 * Returns the tonnage.
	 * @return String
	 */
	public String getTonnage() {
		return tonnage;
	}

	/** 
	 * Set the tonnage.
	 * @param tonnage The tonnage to set
	 */
	public void setTonnage(String tonnage) {
		this.tonnage = tonnage;
	}

	/** 
	 * Returns the carTypeID.
	 * @return String
	 */
	public String getCarTypeID() {
		return carTypeID;
	}

	/** 
	 * Set the carTypeID.
	 * @param carTypeID The carTypeID to set
	 */
	public void setCarTypeID(String carTypeID) {
		this.carTypeID = carTypeID;
	}

	public String getCarID() {
		return carID;
	}

	public void setCarID(String carID) {
		this.carID = carID;
	}
}