/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.global.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-24-2008
 * 
 * XDoclet definition:
 * @struts.form name="lineForm"
 */
public class LineForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** length property */
	private String length;

	/** lineName property */
	private String lineName;

	/** lineNO property */
	private String lineNO;
	
	/** lineID property */
	private String lineID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the length.
	 * @return String
	 */
	public String getLength() {
		return length;
	}

	/** 
	 * Set the length.
	 * @param length The length to set
	 */
	public void setLength(String length) {
		this.length = length;
	}

	/** 
	 * Returns the lineName.
	 * @return String
	 */
	public String getLineName() {
		return lineName;
	}

	/** 
	 * Set the lineName.
	 * @param lineName The lineName to set
	 */
	public void setLineName(String lineName) {
		this.lineName = lineName;
	}

	/** 
	 * Returns the lineNO.
	 * @return String
	 */
	public String getLineNO() {
		return lineNO;
	}

	/** 
	 * Set the lineNO.
	 * @param lineNO The lineNO to set
	 */
	public void setLineNO(String lineNO) {
		this.lineNO = lineNO;
	}

	public String getLineID() {
		return lineID;
	}

	public void setLineID(String lineID) {
		this.lineID = lineID;
	}
}