/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.global.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-24-2008
 * 
 * XDoclet definition:
 * @struts.form name="orderForm"
 */
public class OrderForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** receiveMobile property */
	private String receiveMobile;
	
	/** orderID property */
	private String orderID;

	/** orderNO property */
	private String orderNO;

	/** volume property */
	private String volume;

	/** insurePrice property */
	private String insurePrice;

	/** sendPostCode property */
	private String sendPostCode;

	/** receiveAddress property */
	private String receiveAddress;

	/** remark property */
	private String remark;

	/** receivePostCode property */
	private String receivePostCode;

	/** goodsPrice property */
	private String goodsPrice;

	/** totalPrice property */
	private String totalPrice;

	/** sendAddress property */
	private String sendAddress;

	/** sendMobile property */
	private String sendMobile;

	/** orderStateID property */
	private String orderStateID;

	/** receiveName property */
	private String receiveName;

	/** sendTel property */
	private String sendTel;

	/** receiveTel property */
	private String receiveTel;

	/** weight property */
	private String weight;

	/** sendName property */
	private String sendName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the receiveMobile.
	 * @return String
	 */
	public String getReceiveMobile() {
		return receiveMobile;
	}

	/** 
	 * Set the receiveMobile.
	 * @param receiveMobile The receiveMobile to set
	 */
	public void setReceiveMobile(String receiveMobile) {
		this.receiveMobile = receiveMobile;
	}

	/** 
	 * Returns the orderNO.
	 * @return String
	 */
	public String getOrderNO() {
		return orderNO;
	}

	/** 
	 * Set the orderNO.
	 * @param orderNO The orderNO to set
	 */
	public void setOrderNO(String orderNO) {
		this.orderNO = orderNO;
	}

	/** 
	 * Returns the volume.
	 * @return String
	 */
	public String getVolume() {
		return volume;
	}

	/** 
	 * Set the volume.
	 * @param volume The volume to set
	 */
	public void setVolume(String volume) {
		this.volume = volume;
	}

	/** 
	 * Returns the insurePrice.
	 * @return String
	 */
	public String getInsurePrice() {
		return insurePrice;
	}

	/** 
	 * Set the insurePrice.
	 * @param insurePrice The insurePrice to set
	 */
	public void setInsurePrice(String insurePrice) {
		this.insurePrice = insurePrice;
	}

	/** 
	 * Returns the sendPostCode.
	 * @return String
	 */
	public String getSendPostCode() {
		return sendPostCode;
	}

	/** 
	 * Set the sendPostCode.
	 * @param sendPostCode The sendPostCode to set
	 */
	public void setSendPostCode(String sendPostCode) {
		this.sendPostCode = sendPostCode;
	}

	/** 
	 * Returns the receiveAddress.
	 * @return String
	 */
	public String getReceiveAddress() {
		return receiveAddress;
	}

	/** 
	 * Set the receiveAddress.
	 * @param receiveAddress The receiveAddress to set
	 */
	public void setReceiveAddress(String receiveAddress) {
		this.receiveAddress = receiveAddress;
	}

	/** 
	 * Returns the remark.
	 * @return String
	 */
	public String getRemark() {
		return remark;
	}

	/** 
	 * Set the remark.
	 * @param remark The remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/** 
	 * Returns the receivePostCode.
	 * @return String
	 */
	public String getReceivePostCode() {
		return receivePostCode;
	}

	/** 
	 * Set the receivePostCode.
	 * @param receivePostCode The receivePostCode to set
	 */
	public void setReceivePostCode(String receivePostCode) {
		this.receivePostCode = receivePostCode;
	}

	/** 
	 * Returns the goodsPrice.
	 * @return String
	 */
	public String getGoodsPrice() {
		return goodsPrice;
	}

	/** 
	 * Set the goodsPrice.
	 * @param goodsPrice The goodsPrice to set
	 */
	public void setGoodsPrice(String goodsPrice) {
		this.goodsPrice = goodsPrice;
	}

	/** 
	 * Returns the totalPrice.
	 * @return String
	 */
	public String getTotalPrice() {
		return totalPrice;
	}

	/** 
	 * Set the totalPrice.
	 * @param totalPrice The totalPrice to set
	 */
	public void setTotalPrice(String totalPrice) {
		this.totalPrice = totalPrice;
	}

	/** 
	 * Returns the sendAddress.
	 * @return String
	 */
	public String getSendAddress() {
		return sendAddress;
	}

	/** 
	 * Set the sendAddress.
	 * @param sendAddress The sendAddress to set
	 */
	public void setSendAddress(String sendAddress) {
		this.sendAddress = sendAddress;
	}

	/** 
	 * Returns the sendMobile.
	 * @return String
	 */
	public String getSendMobile() {
		return sendMobile;
	}

	/** 
	 * Set the sendMobile.
	 * @param sendMobile The sendMobile to set
	 */
	public void setSendMobile(String sendMobile) {
		this.sendMobile = sendMobile;
	}

	/** 
	 * Returns the orderStateID.
	 * @return String
	 */
	public String getOrderStateID() {
		return orderStateID;
	}

	/** 
	 * Set the orderStateID.
	 * @param orderStateID The orderStateID to set
	 */
	public void setOrderStateID(String orderStateID) {
		this.orderStateID = orderStateID;
	}

	/** 
	 * Returns the receiveName.
	 * @return String
	 */
	public String getReceiveName() {
		return receiveName;
	}

	/** 
	 * Set the receiveName.
	 * @param receiveName The receiveName to set
	 */
	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	/** 
	 * Returns the sendTel.
	 * @return String
	 */
	public String getSendTel() {
		return sendTel;
	}

	/** 
	 * Set the sendTel.
	 * @param sendTel The sendTel to set
	 */
	public void setSendTel(String sendTel) {
		this.sendTel = sendTel;
	}

	/** 
	 * Returns the receiveTel.
	 * @return String
	 */
	public String getReceiveTel() {
		return receiveTel;
	}

	/** 
	 * Set the receiveTel.
	 * @param receiveTel The receiveTel to set
	 */
	public void setReceiveTel(String receiveTel) {
		this.receiveTel = receiveTel;
	}

	/** 
	 * Returns the weight.
	 * @return String
	 */
	public String getWeight() {
		return weight;
	}

	/** 
	 * Set the weight.
	 * @param weight The weight to set
	 */
	public void setWeight(String weight) {
		this.weight = weight;
	}

	/** 
	 * Returns the sendName.
	 * @return String
	 */
	public String getSendName() {
		return sendName;
	}

	/** 
	 * Set the sendName.
	 * @param sendName The sendName to set
	 */
	public void setSendName(String sendName) {
		this.sendName = sendName;
	}

	public String getOrderID() {
		return orderID;
	}

	public void setOrderID(String orderID) {
		this.orderID = orderID;
	}
}