/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.global.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 11-24-2008
 * 
 * XDoclet definition:
 * @struts.form name="userForm"
 */
public class UserForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** userID property */
	private String userID;

	/** passowrd property */
	private String passowrd;

	/** powerID property */
	private String powerID;

	/** username property */
	private String username;

	/** empID property */
	private String empID;

	/** deliverySpotID property */
	private String deliverySpotID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userID.
	 * @return String
	 */
	public String getUserID() {
		return userID;
	}

	/** 
	 * Set the userID.
	 * @param userID The userID to set
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}

	/** 
	 * Returns the passowrd.
	 * @return String
	 */
	public String getPassowrd() {
		return passowrd;
	}

	/** 
	 * Set the passowrd.
	 * @param passowrd The passowrd to set
	 */
	public void setPassowrd(String passowrd) {
		this.passowrd = passowrd;
	}

	/** 
	 * Returns the powerID.
	 * @return String
	 */
	public String getPowerID() {
		return powerID;
	}

	/** 
	 * Set the powerID.
	 * @param powerID The powerID to set
	 */
	public void setPowerID(String powerID) {
		this.powerID = powerID;
	}

	/** 
	 * Returns the username.
	 * @return String
	 */
	public String getUsername() {
		return username;
	}

	/** 
	 * Set the username.
	 * @param username The username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/** 
	 * Returns the empID.
	 * @return String
	 */
	public String getEmpID() {
		return empID;
	}

	/** 
	 * Set the empID.
	 * @param empID The empID to set
	 */
	public void setEmpID(String empID) {
		this.empID = empID;
	}

	/** 
	 * Returns the deliverySpotID.
	 * @return String
	 */
	public String getDeliverySpotID() {
		return deliverySpotID;
	}

	/** 
	 * Set the deliverySpotID.
	 * @param deliverySpotID The deliverySpotID to set
	 */
	public void setDeliverySpotID(String deliverySpotID) {
		this.deliverySpotID = deliverySpotID;
	}
}