/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.global.struts.action;



import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.global.dao.BaseDao;
import com.global.dao.EmployeeDao;
import com.global.dao.impl.BaseDaoImpl;
import com.global.dao.impl.EmployeeDaoImpl;
import com.global.struts.form.EmployeeForm;
import com.global.struts.form.SelectEmployeeForm;
import com.global.struts.form.UpdataEmployeeForm;
import com.global.vo.Deliveryspot;
import com.global.vo.Employee;
import com.global.vo.Position;

/** 
 * MyEclipse Struts
 * Creation date: 11-24-2008
 * 
 * XDoclet definition:
 * @struts.action path="/employee" name="employeeForm" input="/empManage/addEmp.jsp" scope="request" validate="true"
 */
public class EmployeeAction extends BaseDispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	//添加员工
	public ActionForward addEmployee(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		EmployeeForm employeeForm = (EmployeeForm) form;
		
		Employee emp = new Employee();
		EmployeeDao edao = (EmployeeDao) super.getBean("EmployeeDao");
		Position p = new Position();
		Deliveryspot d = new Deliveryspot();
		
		BaseDao bdao = (BaseDao) super.getBean("BaseDao");
		
		String positionid = employeeForm.getPositionID();
		p = (Position) bdao.get(Position.class, new Integer(positionid));
		
		String deliveryspotid = employeeForm.getDeliverySpotID();
		d = (Deliveryspot) bdao.get(Deliveryspot.class, new Integer(deliveryspotid));
		
		int countEmp = edao.countAllEmp() + 1;
		
		String empno = "D" + deliveryspotid + "E" + countEmp;
		
		String name = employeeForm.getName();
		String address = employeeForm.getAddress();
		String tel = employeeForm.getTel();
		String email = employeeForm.getEmail();
		String cardid = employeeForm.getCardID();
		String salary = employeeForm.getSalary();
		String birthday = employeeForm.getBirthday();
		String startwordtime = employeeForm.getStartWordTime();
		String gender = employeeForm.getGender();
		
		emp.setPosition(p);
		emp.setDeliveryspot(d);
		emp.setAddress(address);
		emp.setCardid(cardid);
		emp.setEmail(email);
		emp.setEmpno(empno);
		emp.setSalary(Double.parseDouble(salary));
		emp.setName(name);
		emp.setGender(gender);
		emp.setTel(tel);
		emp.setBirthday(java.sql.Date.valueOf(birthday));
		emp.setStartwordtime(java.sql.Date.valueOf(startwordtime));
		emp.setFlag(0);
		edao.addEmployee(emp);
		
		HttpSession session = request.getSession();
		request.setAttribute("employeeList", emp);
		
		return mapping.findForward("empList");
	}
	//从数据库获取职位列表
	public ActionForward listPosition(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		EmployeeForm employeeForm = (EmployeeForm) form;
		EmployeeDao empd = (EmployeeDao) super.getBean("EmployeeDao");
		List positionList = new ArrayList();
		HttpSession session = request.getSession();
		
		positionList = empd.listPosition();
		request.setAttribute("positionList",positionList);
		
		return mapping.getInputForward();
	}
	//从数据库获取配送点列表
	public ActionForward listDeliverySpot(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response){
		EmployeeForm employeeForm = (EmployeeForm) form;
		EmployeeDao empd = (EmployeeDao) super.getBean("EmployeeDao");
		List deliverySpotList = new ArrayList();
		HttpSession session = request.getSession();
		
		deliverySpotList = empd.listDeliverySpot();
		request.setAttribute("deliverySpotList",deliverySpotList);
		
		
		return listPosition(mapping,form,request,response);
	}	

}