/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.global.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.global.dao.UserDao;
import com.global.struts.form.LoginForm;
import com.global.vo.User;

/** 
 * MyEclipse Struts
 * Creation date: 11-24-2008
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/form/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends BaseDispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		UserDao dao  =  (UserDao) getBean("UserDao");
		User u = dao.login(loginForm.getUsername().trim(), loginForm.getPassword().trim(), Integer.parseInt(request.getParameter("powerID")));
		
		
		String msg = null;
		if(u!=null){
			HttpSession session = request.getSession();
			session.setAttribute("UserSession", u);
			if(loginForm.getPowerID().equals("1")){
			    return mapping.findForward("super");
			}
			else if(loginForm.getPowerID().equals("2")){
				return mapping.findForward("manager");
			}
			else if(loginForm.getPowerID().equals("3")){
				return mapping.findForward("operater");
			}
		}
		else
		    msg = "<font color=red>用户名或密码错误!请重试！</font>";
			request.setAttribute("Login_Error", msg);
			return mapping.getInputForward();
	}
	
	public ActionForward loginOut(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		    LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
			HttpSession session = request.getSession();
			User u = (User) session.getAttribute("UserSession");
			if(u != null){
				session.setAttribute("UserSession", null);
			}
			return mapping.getInputForward();
	}
}