package com.global.vo;

import java.util.Date;

/**
 * Car generated by MyEclipse Persistence Tools
 */

public class Car implements java.io.Serializable {

	// Fields

	private Integer carid;

	private Line line;

	private Employee employee;

	private Cartype cartype;

	private Carstate carstate;

	private String carno;

	private String workno;

	private Double carsize;

	private Double tonnage;

	private Date buytime;

	private String leavetime;

	private String remark;

	// Constructors

	/** default constructor */
	public Car() {
	}

	/** full constructor */
	public Car(Line line, Employee employee, Cartype cartype,
			Carstate carstate, String carno, String workno, Double carsize,
			Double tonnage, Date buytime, String leavetime, String remark) {
		this.line = line;
		this.employee = employee;
		this.cartype = cartype;
		this.carstate = carstate;
		this.carno = carno;
		this.workno = workno;
		this.carsize = carsize;
		this.tonnage = tonnage;
		this.buytime = buytime;
		this.leavetime = leavetime;
		this.remark = remark;
	}

	// Property accessors

	public Integer getCarid() {
		return this.carid;
	}

	public void setCarid(Integer carid) {
		this.carid = carid;
	}

	public Line getLine() {
		return this.line;
	}

	public void setLine(Line line) {
		this.line = line;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Cartype getCartype() {
		return this.cartype;
	}

	public void setCartype(Cartype cartype) {
		this.cartype = cartype;
	}

	public Carstate getCarstate() {
		return this.carstate;
	}

	public void setCarstate(Carstate carstate) {
		this.carstate = carstate;
	}

	public String getCarno() {
		return this.carno;
	}

	public void setCarno(String carno) {
		this.carno = carno;
	}

	public String getWorkno() {
		return this.workno;
	}

	public void setWorkno(String workno) {
		this.workno = workno;
	}

	public Double getCarsize() {
		return this.carsize;
	}

	public void setCarsize(Double carsize) {
		this.carsize = carsize;
	}

	public Double getTonnage() {
		return this.tonnage;
	}

	public void setTonnage(Double tonnage) {
		this.tonnage = tonnage;
	}

	public Date getBuytime() {
		return this.buytime;
	}

	public void setBuytime(Date buytime) {
		this.buytime = buytime;
	}

	public String getLeavetime() {
		return this.leavetime;
	}

	public void setLeavetime(String leavetime) {
		this.leavetime = leavetime;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}