package com.global.vo;

import java.util.HashSet;
import java.util.Set;

/**
 * Cartype generated by MyEclipse Persistence Tools
 */

public class Cartype implements java.io.Serializable {

	// Fields

	private Integer cartypeid;

	private String name;

	private Set cars = new HashSet(0);

	// Constructors

	/** default constructor */
	public Cartype() {
	}

	/** full constructor */
	public Cartype(String name, Set cars) {
		this.name = name;
		this.cars = cars;
	}

	// Property accessors

	public Integer getCartypeid() {
		return this.cartypeid;
	}

	public void setCartypeid(Integer cartypeid) {
		this.cartypeid = cartypeid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getCars() {
		return this.cars;
	}

	public void setCars(Set cars) {
		this.cars = cars;
	}

}