package com.global.vo;

import java.util.HashSet;
import java.util.Set;



/**
 * City generated by MyEclipse Persistence Tools
 */

public class City implements java.io.Serializable {

	// Fields

	private Integer cityid;

	private String name;

	private Province province;

	private Set deliveryspots = new HashSet(0);

	// Constructors

	/** default constructor */
	public City() {
	}

	/** full constructor */
	

	// Property accessors

	public Integer getCityid() {
		return this.cityid;
	}

	public void setCityid(Integer cityid) {
		this.cityid = cityid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public City(Integer cityid, String name, Province province, Set deliveryspots) {
		super();
		this.cityid = cityid;
		this.name = name;
		this.province = province;
		this.deliveryspots = deliveryspots;
	}

	public Province getProvince() {
		return province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public Set getDeliveryspots() {
		return this.deliveryspots;
	}

	public void setDeliveryspots(Set deliveryspots) {
		this.deliveryspots = deliveryspots;
	}

}