package com.global.vo;

import java.util.HashSet;
import java.util.Set;

/**
 * Deliveryspot generated by MyEclipse Persistence Tools
 */

public class Deliveryspot implements java.io.Serializable {

	// Fields

	private Integer deliveryspotid;

	private Province province;

	private Employee employee;

	private City city;

	private String deliveryspotno;

	private String name;

	private String tel;

	private Integer flag;

	private Double startscope;

	private Double startprice;

	private Double secondprice;

	private Double startvolumescope;

	private Double startvolumeprice;

	private Double secondvolumeprice;

	private Set receipts = new HashSet(0);

	private Set linedetailes = new HashSet(0);

	private Set uses = new HashSet(0);

	private Set employees = new HashSet(0);

	private Set oders = new HashSet(0);

	// Constructors

	/** default constructor */
	public Deliveryspot() {
	}

	/** full constructor */
	public Deliveryspot(Province province, Employee employee, City city,
			String deliveryspotno, String name, String tel, Double startscope,
			Double startprice, Double secondprice, Set receipts,
			Set linedetailes, Set uses, Set employees, Set oders) {
		this.province = province;
		this.employee = employee;
		this.city = city;
		this.deliveryspotno = deliveryspotno;
		this.name = name;
		this.tel = tel;
		this.startscope = startscope;
		this.startprice = startprice;
		this.secondprice = secondprice;
		this.receipts = receipts;
		this.linedetailes = linedetailes;
		this.uses = uses;
		this.employees = employees;
		this.oders = oders;
	}

	// Property accessors

	public Integer getDeliveryspotid() {
		return this.deliveryspotid;
	}

	public void setDeliveryspotid(Integer deliveryspotid) {
		this.deliveryspotid = deliveryspotid;
	}

	public Province getProvince() {
		return this.province;
	}

	public void setProvince(Province province) {
		this.province = province;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	public String getDeliveryspotno() {
		return this.deliveryspotno;
	}

	public void setDeliveryspotno(String deliveryspotno) {
		this.deliveryspotno = deliveryspotno;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Double getStartscope() {
		return this.startscope;
	}

	public void setStartscope(Double startscope) {
		this.startscope = startscope;
	}

	public Double getStartprice() {
		return this.startprice;
	}

	public void setStartprice(Double startprice) {
		this.startprice = startprice;
	}

	public Double getSecondprice() {
		return this.secondprice;
	}

	public void setSecondprice(Double secondprice) {
		this.secondprice = secondprice;
	}

	public Set getReceipts() {
		return this.receipts;
	}

	public void setReceipts(Set receipts) {
		this.receipts = receipts;
	}

	public Set getLinedetailes() {
		return this.linedetailes;
	}

	public void setLinedetailes(Set linedetailes) {
		this.linedetailes = linedetailes;
	}

	public Set getUses() {
		return this.uses;
	}

	public void setUses(Set uses) {
		this.uses = uses;
	}

	public Set getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set employees) {
		this.employees = employees;
	}

	public Set getOders() {
		return this.oders;
	}

	public void setOders(Set oders) {
		this.oders = oders;
	}

	public Integer getFlag() {
		return flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public Double getSecondvolumeprice() {
		return secondvolumeprice;
	}

	public void setSecondvolumeprice(Double secondvolumeprice) {
		this.secondvolumeprice = secondvolumeprice;
	}

	public Double getStartvolumeprice() {
		return startvolumeprice;
	}

	public void setStartvolumeprice(Double startvolumeprice) {
		this.startvolumeprice = startvolumeprice;
	}

	public Double getStartvolumescope() {
		return startvolumescope;
	}

	public void setStartvolumescope(Double startvolumescope) {
		this.startvolumescope = startvolumescope;
	}

}