package com.global.vo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by MyEclipse Persistence Tools
 */

public class Employee implements java.io.Serializable {

	// Fields

	private Integer empid;

	private Deliveryspot deliveryspot;

	private Position position;

	private String empno;

	private String name;

	private String gender;

	private Date birthday;

	private String address;

	private String tel;

	private Date startwordtime;

	private Double salary;

	private String email;

	private String cardid;

	private Integer flag;

	private Set uses = new HashSet(0);

	private Set cars = new HashSet(0);

	private Set deliveryspots = new HashSet(0);
	
	private Set receipts = new HashSet(0);

	// Constructors

	public Set getReceipts() {
		return receipts;
	}

	public void setReceipts(Set receipts) {
		this.receipts = receipts;
	}

	/** default constructor */
	public Employee() {
	}

	/** full constructor */
	public Employee(Deliveryspot deliveryspot, Position position, String empno,
			String name, String gender, Date birthday, String address,
			String tel, Date startwordtime, Double salary, String email,
			String cardid, Integer flag, Set uses, Set cars, Set deliveryspots) {
		this.deliveryspot = deliveryspot;
		this.position = position;
		this.empno = empno;
		this.name = name;
		this.gender = gender;
		this.birthday = birthday;
		this.address = address;
		this.tel = tel;
		this.startwordtime = startwordtime;
		this.salary = salary;
		this.email = email;
		this.cardid = cardid;
		this.flag = flag;
		this.uses = uses;
		this.cars = cars;
		this.deliveryspots = deliveryspots;
	}

	// Property accessors

	public Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	public Deliveryspot getDeliveryspot() {
		return this.deliveryspot;
	}

	public void setDeliveryspot(Deliveryspot deliveryspot) {
		this.deliveryspot = deliveryspot;
	}

	public Position getPosition() {
		return this.position;
	}

	public void setPosition(Position position) {
		this.position = position;
	}

	public String getEmpno() {
		return this.empno;
	}

	public void setEmpno(String empno) {
		this.empno = empno;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public Date getStartwordtime() {
		return this.startwordtime;
	}

	public void setStartwordtime(Date startwordtime) {
		this.startwordtime = startwordtime;
	}

	public Double getSalary() {
		return this.salary;
	}

	public void setSalary(Double salary) {
		this.salary = salary;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCardid() {
		return this.cardid;
	}

	public void setCardid(String cardid) {
		this.cardid = cardid;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public Set getUses() {
		return this.uses;
	}

	public void setUses(Set uses) {
		this.uses = uses;
	}

	public Set getCars() {
		return this.cars;
	}

	public void setCars(Set cars) {
		this.cars = cars;
	}

	public Set getDeliveryspots() {
		return this.deliveryspots;
	}

	public void setDeliveryspots(Set deliveryspots) {
		this.deliveryspots = deliveryspots;
	}

}