package com.global.vo;

import java.util.HashSet;
import java.util.Set;

/**
 * Line generated by MyEclipse Persistence Tools
 */

public class Line implements java.io.Serializable {

	// Fields

	private Integer lineid;

	private String lineno;

	private String linename;

	private Double length;

	private Set receipts = new HashSet(0);

	private Set linedetailes = new HashSet(0);

	private Set cars = new HashSet(0);

	// Constructors

	/** default constructor */
	public Line() {
	}

	/** full constructor */
	public Line(String lineno, String linename, Double length, Set receipts,
			Set linedetailes, Set cars) {
		this.lineno = lineno;
		this.linename = linename;
		this.length = length;
		this.receipts = receipts;
		this.linedetailes = linedetailes;
		this.cars = cars;
	}

	// Property accessors

	public Integer getLineid() {
		return this.lineid;
	}

	public void setLineid(Integer lineid) {
		this.lineid = lineid;
	}

	public String getLineno() {
		return this.lineno;
	}

	public void setLineno(String lineno) {
		this.lineno = lineno;
	}

	public String getLinename() {
		return this.linename;
	}

	public void setLinename(String linename) {
		this.linename = linename;
	}

	public Double getLength() {
		return this.length;
	}

	public void setLength(Double length) {
		this.length = length;
	}

	public Set getReceipts() {
		return this.receipts;
	}

	public void setReceipts(Set receipts) {
		this.receipts = receipts;
	}

	public Set getLinedetailes() {
		return this.linedetailes;
	}

	public void setLinedetailes(Set linedetailes) {
		this.linedetailes = linedetailes;
	}

	public Set getCars() {
		return this.cars;
	}

	public void setCars(Set cars) {
		this.cars = cars;
	}

}