package com.global.vo;

import java.util.HashSet;
import java.util.Set;

/**
 * Orderstate generated by MyEclipse Persistence Tools
 */

public class Orderstate implements java.io.Serializable {

	// Fields

	private Integer orderstateid;

	private String name;

	private Set oders = new HashSet(0);

	// Constructors

	/** default constructor */
	public Orderstate() {
	}

	/** full constructor */
	public Orderstate(String name, Set oders) {
		this.name = name;
		this.oders = oders;
	}

	// Property accessors

	public Integer getOrderstateid() {
		return this.orderstateid;
	}

	public void setOrderstateid(Integer orderstateid) {
		this.orderstateid = orderstateid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getOders() {
		return this.oders;
	}

	public void setOders(Set oders) {
		this.oders = oders;
	}

}