package com.global.vo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oder generated by MyEclipse Persistence Tools
 */

public class Order implements java.io.Serializable {

	// Fields

	private Integer orderid;

	private Deliveryspot deliveryspot;

	private Orderstate orderstate;

	private String orderno;

	private String sendname;

	private String sendaddress;

	private String sendtel;

	private String sendmobile;

	private String sendpostcode;

	private String receivename;

	private String receiveaddress;

	private String receivetel;

	private String receivemobile;

	private String receivepostcode;

	private Double totalprice;

	private Double insureprice;

	private Double goodsprice;

	private Double volume;

	private Double weight;

	private String remark;

	private Date createtime;

	private Set receiptdetailes = new HashSet(0);

	// Constructors

	/** default constructor */
	public Order() {
	}

	/** full constructor */
	public Order(Deliveryspot deliveryspot, Orderstate orderstate,
			String orderno, String sendname, String sendaddress,
			String sendtel, String sendmobile, String sendpostcode,
			String receivename, String receiveaddress, String receivetel,
			String receivemobile, String receivepostcode, Double totalprice,
			Double insureprice, Double goodsprice, Double volume,
			Double weight, String remark, Date createtime, Set receiptdetailes) {
		this.deliveryspot = deliveryspot;
		this.orderstate = orderstate;
		this.orderno = orderno;
		this.sendname = sendname;
		this.sendaddress = sendaddress;
		this.sendtel = sendtel;
		this.sendmobile = sendmobile;
		this.sendpostcode = sendpostcode;
		this.receivename = receivename;
		this.receiveaddress = receiveaddress;
		this.receivetel = receivetel;
		this.receivemobile = receivemobile;
		this.receivepostcode = receivepostcode;
		this.totalprice = totalprice;
		this.insureprice = insureprice;
		this.goodsprice = goodsprice;
		this.volume = volume;
		this.weight = weight;
		this.remark = remark;
		this.createtime = createtime;
		this.receiptdetailes = receiptdetailes;
	}

	// Property accessors

	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	public Deliveryspot getDeliveryspot() {
		return this.deliveryspot;
	}

	public void setDeliveryspot(Deliveryspot deliveryspot) {
		this.deliveryspot = deliveryspot;
	}

	public Orderstate getOrderstate() {
		return this.orderstate;
	}

	public void setOrderstate(Orderstate orderstate) {
		this.orderstate = orderstate;
	}

	public String getOrderno() {
		return this.orderno;
	}

	public void setOrderno(String orderno) {
		this.orderno = orderno;
	}

	public String getSendname() {
		return this.sendname;
	}

	public void setSendname(String sendname) {
		this.sendname = sendname;
	}

	public String getSendaddress() {
		return this.sendaddress;
	}

	public void setSendaddress(String sendaddress) {
		this.sendaddress = sendaddress;
	}

	public String getSendtel() {
		return this.sendtel;
	}

	public void setSendtel(String sendtel) {
		this.sendtel = sendtel;
	}

	public String getSendmobile() {
		return this.sendmobile;
	}

	public void setSendmobile(String sendmobile) {
		this.sendmobile = sendmobile;
	}

	public String getSendpostcode() {
		return this.sendpostcode;
	}

	public void setSendpostcode(String sendpostcode) {
		this.sendpostcode = sendpostcode;
	}

	public String getReceivename() {
		return this.receivename;
	}

	public void setReceivename(String receivename) {
		this.receivename = receivename;
	}

	public String getReceiveaddress() {
		return this.receiveaddress;
	}

	public void setReceiveaddress(String receiveaddress) {
		this.receiveaddress = receiveaddress;
	}

	public String getReceivetel() {
		return this.receivetel;
	}

	public void setReceivetel(String receivetel) {
		this.receivetel = receivetel;
	}

	public String getReceivemobile() {
		return this.receivemobile;
	}

	public void setReceivemobile(String receivemobile) {
		this.receivemobile = receivemobile;
	}

	public String getReceivepostcode() {
		return this.receivepostcode;
	}

	public void setReceivepostcode(String receivepostcode) {
		this.receivepostcode = receivepostcode;
	}

	public Double getTotalprice() {
		return this.totalprice;
	}

	public void setTotalprice(Double totalprice) {
		this.totalprice = totalprice;
	}

	public Double getInsureprice() {
		return this.insureprice;
	}

	public void setInsureprice(Double insureprice) {
		this.insureprice = insureprice;
	}

	public Double getGoodsprice() {
		return this.goodsprice;
	}

	public void setGoodsprice(Double goodsprice) {
		this.goodsprice = goodsprice;
	}

	public Double getVolume() {
		return this.volume;
	}

	public void setVolume(Double volume) {
		this.volume = volume;
	}

	public Double getWeight() {
		return this.weight;
	}

	public void setWeight(Double weight) {
		this.weight = weight;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Set getReceiptdetailes() {
		return this.receiptdetailes;
	}

	public void setReceiptdetailes(Set receiptdetailes) {
		this.receiptdetailes = receiptdetailes;
	}

}