package com.global.vo;

import java.util.HashSet;
import java.util.Set;

/**
 * Power generated by MyEclipse Persistence Tools
 */

public class Power implements java.io.Serializable {

	// Fields

	private Integer powerid;

	private String name;

	private Set uses = new HashSet(0);

	// Constructors

	/** default constructor */
	public Power() {
	}

	/** full constructor */
	public Power(String name, Set uses) {
		this.name = name;
		this.uses = uses;
	}

	// Property accessors

	public Integer getPowerid() {
		return this.powerid;
	}

	public void setPowerid(Integer powerid) {
		this.powerid = powerid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUses() {
		return this.uses;
	}

	public void setUses(Set uses) {
		this.uses = uses;
	}

}