package com.global.vo;

import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by MyEclipse Persistence Tools
 */

public class Province implements java.io.Serializable {

	// Fields

	private Integer provinceid;

	private String name;

	private Set deliveryspots = new HashSet(0);
	
	private Set cities = new HashSet(0);

	// Constructors

	public Set getCities() {
		return cities;
	}

	public void setCities(Set cities) {
		this.cities = cities;
	}

	/** default constructor */
	public Province() {
	}

	/** full constructor */
	public Province(String name, Set deliveryspots) {
		this.name = name;
		this.deliveryspots = deliveryspots;
	}

	// Property accessors

	public Integer getProvinceid() {
		return this.provinceid;
	}

	public void setProvinceid(Integer provinceid) {
		this.provinceid = provinceid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getDeliveryspots() {
		return this.deliveryspots;
	}

	public void setDeliveryspots(Set deliveryspots) {
		this.deliveryspots = deliveryspots;
	}

}