package com.global.vo;

/**
 * Receiptdetaile generated by MyEclipse Persistence Tools
 */

public class Receiptdetaile implements java.io.Serializable {

	// Fields

	private Integer rdid;

	private Receipt receipt;

	private Order oder;

	// Constructors

	/** default constructor */
	public Receiptdetaile() {
	}

	/** full constructor */
	public Receiptdetaile(Receipt receipt, Order oder) {
		this.receipt = receipt;
		this.oder = oder;
	}

	// Property accessors

	public Integer getRdid() {
		return this.rdid;
	}

	public void setRdid(Integer rdid) {
		this.rdid = rdid;
	}

	public Receipt getReceipt() {
		return this.receipt;
	}

	public void setReceipt(Receipt receipt) {
		this.receipt = receipt;
	}

	public Order getOder() {
		return this.oder;
	}

	public void setOder(Order oder) {
		this.oder = oder;
	}

}